name: Deployment Exercise 2

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying"